spring.application.name=bms_jul_2026

spring.datasource.url=jdbc:mysql://localhost:3306/bms_jul_2026
spring.datasource.username=bms_jul_2026_user
#spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

server.port=8081